install:
	@echo Setting up tmux configuration.
	@cp tmux.conf ~/.tmux.conf
	@cp .bashrc ~/.bashrc
	@cp .inputrc ~/.inputrc
	@cp .bash_profile ~/.bash_profile
	@echo Done setting up tmux configuration.
