install:
	@echo Setting up bash configuration
	@cp .git-completion.bash ~/.git-completion.bash
	@cp .bashrc ~/.bashrc
	@cp .inputrc ~/.inputrc
	@cp .bash_profile ~/.bash_profile
	@echo Done setting up bash configuration.
